version: "3.7"
services:
  workspace:
    build:
      args:
        user: thuan
        uid: 1000
      context: ./
      dockerfile: ./Dockerfile
    image: workspace
    container_name: workspace
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - local
  db:
    image: mysql:8.0
    container_name: docker_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - local
  nginx:
    image: nginx:1.17-alpine
    container_name: docker_nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ../:/var/www
      - ./nginx/config:/etc/nginx/sites-available
      - ./nginx/logs:/var/log/nginx
    networks:
      - local
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY:1
      - PMA_HOST:db
      - MYSQL_USERNAME:${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD:${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - local
networks:
  local:
    driver: bridge
